/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.MainController;

import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import views.customers.CustomerPhysicalView;

/**
 *
 * @author jonat
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    private final JDesktopPane desktop = new JDesktopPane();

    private final MainController mainController = new MainController(this);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setContentPane(desktop);
    }

    protected void createFrame(JInternalFrame frame) {
        System.out.println("teste");
        
        try {
            frame.setSelected(true);
            frame.setEnabled(true);
             desktop.add(frame);
            frame.setVisible(true);
        } catch (final PropertyVetoException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuCreateDatabase = new javax.swing.JMenuItem();
        menuCreateTables = new javax.swing.JMenuItem();
        menuRunSeeds = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Banco de Dados");

        menuCreateDatabase.setText("Gerar Banco de Dados");
        menuCreateDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateDatabaseActionPerformed(evt);
            }
        });
        jMenu2.add(menuCreateDatabase);

        menuCreateTables.setText("Gerar Tabelas");
        menuCreateTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateTablesActionPerformed(evt);
            }
        });
        jMenu2.add(menuCreateTables);

        menuRunSeeds.setText("Popular Tabelas");
        menuRunSeeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRunSeedsActionPerformed(evt);
            }
        });
        jMenu2.add(menuRunSeeds);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Gerenciar");

        jMenu4.setText("Clientes");

        jMenuItem6.setText("Pessoa Física");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Pessoa Jurídica");
        jMenu4.add(jMenuItem7);

        jMenu3.add(jMenu4);

        jMenu5.setText("Pedidos de Venda");

        jMenuItem8.setText("Novo Orçamento");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Listar Orçamentos");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Listar Vendas");
        jMenu5.add(jMenuItem10);

        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Relatórios");

        jMenuItem12.setText("Pedidos");
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Produtos mais vendidos");
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("Carrinhos Abandonados");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("Vendedores");
        jMenu6.add(jMenuItem15);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCreateDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateDatabaseActionPerformed
        mainController.handleGenerateDatabase();
    }//GEN-LAST:event_menuCreateDatabaseActionPerformed

    private void menuRunSeedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRunSeedsActionPerformed
        mainController.handleRunSeedsMigration();
    }//GEN-LAST:event_menuRunSeedsActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        createFrame(new CustomerPhysicalView());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuCreateTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateTablesActionPerformed
        mainController.handleRunTablesMigration();
    }//GEN-LAST:event_menuCreateTablesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuCreateDatabase;
    private javax.swing.JMenuItem menuCreateTables;
    private javax.swing.JMenuItem menuRunSeeds;
    // End of variables declaration//GEN-END:variables
}
