-- CREATE DATABASE IF NOT EXISTS sales_order_module;

-- USE sales_order_module;

CREATE TABLE IF NOT EXISTS sellers (
   `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `name` VARCHAR(255) NOT NULL,
   `cnpj` VARCHAR(14) NOT NULL UNIQUE,
   `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
   `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers_legal (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `cnpj` VARCHAR(14) NOT NULL UNIQUE,
  `responsible_name` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - INACTIVE, 1 - ACTIVE, 2 - BLOCKED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers_physical (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `cpf` VARCHAR(11) NOT NULL UNIQUE,
  `birth_date` DATE NOT NULL,
  `gender` TINYINT(1) NOT NULL DEFAULT 4 COMMENT '1 - MASCULINE, 2 - FEMININE, 3 - OTHER, 4 - NOT_SPECIFIED', 
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - INACTIVE, 1 - ACTIVE, 2 - BLOCKED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS addresses (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `customer_id` INT(8) NOT NULL,
  `customer_type` TINYINT(1) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `district` VARCHAR(255) NOT NULL UNIQUE,
  `city` VARCHAR(11) NOT NULL UNIQUE,
  `number` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `promotional_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `quantity` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `photo` LONGTEXT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - INACTIVE, 1 - ACTIVE',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carts (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `customer_id` INT(8) NOT NULL,
  `customer_type` TINYINT(1) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 - ACTIVE, 2 - ABANDONED, 3 - CLOSED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_items (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cart_id` INT(8) NOT NULL,
  `item_id` INT(8) NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT cart_items_carts_cart_id_fk FOREIGN KEY (cart_id) REFERENCES carts(id),
  CONSTRAINT cart_items_items_item_id_fk FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS orders (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `customer_id` INT(8) NOT NULL,
  `customer_type` TINYINT(1) NOT NULL,
  `seller_id` INT(8) NOT NULL,
  `cart_id` INT(8) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 - PENDING, 2 - PAID, 3 - CANCELED, 4 - READY_TO_DELIVERING, 5 - SHIPPED, 6 - DELIVERED, 7 - CLOSED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT orders_seller_seller_id FOREIGN KEY (seller_id) REFERENCES sellers(id),
  CONSTRAINT orders_carts_cart_id_fk FOREIGN KEY (cart_id) REFERENCES carts(id)
);

CREATE TABLE IF NOT EXISTS order_items (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT(8) NOT NULL,
  `item_id` INT(8) NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `item_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `quantity` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT order_items_items_item_id_fk FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS orders_history (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT(8) NOT NULL,
  `comment` LONGTEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 - PENDING, 2 - PAID, 3 - CANCELED, 4 - READY_TO_DELIVERING, 5 - SHIPPED, 6 - DELIVERED, 7 - CLOSED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT orders_history_orders_order_id_fk FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE IF NOT EXISTS order_payments (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT(8) NOT NULL,
  `payment_method` ENUM('cash', 'credit_card', 'debit_card', 'pix', 'bank_slip') NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `installments` INT(2) NOT NULL DEFAULT 1,
  `additions` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `discounts` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `shipping_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT order_payments_orders_order_id_fk FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE IF NOT EXISTS order_shipments (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT(8) NOT NULL,
  `address_id` INT(8) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `shipment_type` VARCHAR(255) NOT NULL,
  `shipment_values` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT order_shipments_orders_order_id_fk FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT order_shipments_addresses_address_id_fk FOREIGN KEY (address_id) REFERENCES addresses(id)
)