-- CREATE DATABASE IF NOT EXISTS sales_order_module;

-- USE sales_order_module;

CREATE TABLE IF NOT EXISTS customers_legal (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `cnpj` VARCHAR(14) NOT NULL UNIQUE,
  `responsible_name` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - INACTIVE, 1 - ACTIVE, 2 - BLOCKED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers_physical (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `cpf` VARCHAR(11) NOT NULL UNIQUE,
  `birth_date` DATE NOT NULL,
  `gender` TINYINT(1) NOT NULL DEFAULT 4 COMMENT '1 - MASCULINE, 2 - FEMININE, 3 - OTHER, 4 - NOT_SPECIFIED', 
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - INACTIVE, 1 - ACTIVE, 2 - BLOCKED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `promotional_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `quantity` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `photo` LONGTEXT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - INACTIVE, 1 - ACTIVE',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carts (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `customer_id` INT(8) NOT NULL,
  `customer_type` TINYINT(1) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 - ACTIVE, 2 - ABANDONED, 3 - CLOSED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_items (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cart_id` INT(8) NOT NULL,
  `item_id` INT(8) NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `customer_id` INT(8) NOT NULL,
  `customer_type` TINYINT(1) NOT NULL,
  `seller_id` INT(8) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 - PENDING, 2 - PAID, 3 - CANCELED, 4 - READY_TO_DELIVERING, 5 - SHIPPED, 6 - DELIVERED, 7 - CLOSED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS order_items (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT(8) NOT NULL,
  `item_id` INT(8) NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders_history (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT(8) NOT NULL,
  `comment` LONGTEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 - PENDING, 2 - PAID, 3 - CANCELED, 4 - READY_TO_DELIVERING, 5 - SHIPPED, 6 - DELIVERED, 7 - CLOSED',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_payments (
  `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` INT(8) NOT NULL,
  `payment_method` ENUM('cash', 'credit_card', 'debit_card', 'pix', 'bank_slip') NOT NULL,
  `additions` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `discounts` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `shipping_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);